--https://school.programmers.co.kr/learn/courses/30/lessons/131529

SELECT  CASE   
        WHEN PRODUCT_ID IN (1,2) THEN 'A1'
        WHEN PRODUCT_ID IN (3,4,5) THEN 'C3'
        WHEN PRODUCT_ID = 6 THEN 'K1'
    END AS CATEGORY,
    COUNT(*) PRODUCTS
from product
WHERE    CASE   
        WHEN PRODUCT_ID IN (1,2) THEN 'A1'
        WHEN PRODUCT_ID IN (3,4,5) THEN 'C3'
        WHEN PRODUCT_ID = 6 THEN 'K1'
    END IN ('A1', 'C3', 'K1')
group by CASE   
        WHEN PRODUCT_ID IN (1,2) THEN 'A1'
        WHEN PRODUCT_ID IN (3,4,5) THEN 'C3'
        WHEN PRODUCT_ID = 6 THEN 'K1'
    END
ORDER BY CATEGORY
SELECT ANIMAL_ID,NAME, 

CASE    WHEN SEX_UPON_INTAKE LIKE 'Neutered%' THEN 'O'
        WHEN SEX_UPON_INTAKE LIKE 'Spayed%' THEN 'O'
        ELSE 'X'
        END 중성화
FROM ANIMAL_INS

-- 코드를 입력하세요
SELECT CASE
    WHEN TO_CHAR(DATETIME,'HH24') = 9 THEN '9'
    WHEN TO_CHAR(DATETIME,'HH24') = 10 THEN '10'
    WHEN TO_CHAR(DATETIME,'HH24') = 11 THEN '11'
    WHEN TO_CHAR(DATETIME,'HH24') = 12 THEN '12'
    WHEN TO_CHAR(DATETIME,'HH24') = 13 THEN '13'
    WHEN TO_CHAR(DATETIME,'HH24') = 14 THEN '14'
    WHEN TO_CHAR(DATETIME,'HH24') = 15 THEN '15'
    WHEN TO_CHAR(DATETIME,'HH24') = 16 THEN '16'
    WHEN TO_CHAR(DATETIME,'HH24') = 17 THEN '17'
    WHEN TO_CHAR(DATETIME,'HH24') = 18 THEN '18'
    WHEN TO_CHAR(DATETIME,'HH24') = 19 THEN '19'
    END AS HOUR, COUNT(ANIMAL_ID)
from ANIMAL_OUTS
WHERE TO_CHAR(DATETIME,'HH24') BETWEEN 9 AND 19
GROUP BY TO_CHAR(DATETIME, 'HH24')

ORDER BY TO_CHAR(DATETIME, 'HH24')

SELECT P.PRODUCT_CODE,P.PRICE, COUNT(P.PRODUCT_CODE) AS SALES
from product P RIGHT JOIN OFFLINE_SALE O ON P.product_ID = O.product_ID
group by P.PRODUCT_CODE, P.PRICE
order by SALES, p.product_code